<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_model extends CI_Model
{

    public $table = 'data';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,provinsi,kabupaten,faskes,nik,nama,jenis_kelamin,kelompok_usia,kategori,sub_kategori,kanal,status,nikdisduk,nama_lengkap,alamat,no_rt,no_rw,no_prop,nama_prop,no_kab,nama_kab,no_kec,nama_kec,no_kel,nama_kel,puskesmas');
        $this->datatables->from('data');
        //add this line for join
        //$this->datatables->join('table2', 'data.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('data/read/$1'),'Read')." | ".anchor(site_url('data/update/$1'),'Update')." | ".anchor(site_url('data/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('faskes', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('kelompok_usia', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('sub_kategori', $q);
	$this->db->or_like('kanal', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('nikdisduk', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_rt', $q);
	$this->db->or_like('no_rw', $q);
	$this->db->or_like('no_prop', $q);
	$this->db->or_like('nama_prop', $q);
	$this->db->or_like('no_kab', $q);
	$this->db->or_like('nama_kab', $q);
	$this->db->or_like('no_kec', $q);
	$this->db->or_like('nama_kec', $q);
	$this->db->or_like('no_kel', $q);
	$this->db->or_like('nama_kel', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('faskes', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('kelompok_usia', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('sub_kategori', $q);
	$this->db->or_like('kanal', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('nikdisduk', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_rt', $q);
	$this->db->or_like('no_rw', $q);
	$this->db->or_like('no_prop', $q);
	$this->db->or_like('nama_prop', $q);
	$this->db->or_like('no_kab', $q);
	$this->db->or_like('nama_kab', $q);
	$this->db->or_like('no_kec', $q);
	$this->db->or_like('nama_kec', $q);
	$this->db->or_like('no_kel', $q);
	$this->db->or_like('nama_kel', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_model.php */
/* Location: ./application/models/Data_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-29 11:16:49 */
/* http://harviacode.com */