<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penduduk_model extends CI_Model
{

    public $table = 'penduduk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        //anchor(site_url('penduduk/read/$1'),'Read')." | ".
        $option =' <div class="dropdown relative"> <button class="dropdown-toggle button inline-block bg-theme-1 text-white">Aksi</button> <div class="dropdown-box mt-10 absolute w-40 top-0 left-0 z-20"> <div class="dropdown-box__content box p-2"> <!--a href="cetak/word/$1" class="block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md">Print</a--> <a href="penduduk/update/$1" class="block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md">Update</a> <a href="penduduk/delete/$1" class="block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md" onclick="javasciprt: return confirm(\'Are You Sure ?\')">Delete</a></div> </div> </div> ';

        $this->datatables->select('id,nik,nama,jenis_kelamin,nama_lengkap,alamat,no_rt,no_rw,no_prop,nama_prop,no_kab,nama_kab,no_kec,nama_kec,no_kel,nama_kel');
        $this->datatables->from('penduduk');
        //add this line for join
        //$this->datatables->join('table2', 'penduduk.field = table2.field');
        $this->datatables->add_column('action',$option, 'id');
      //  $this->datatables->add_column('action', anchor(site_url('penduduk/update/$1'),'Update')." | ".anchor(site_url('penduduk/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_nik($id)
    {
        $this->db->where('nik', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_rt', $q);
	$this->db->or_like('no_rw', $q);
	$this->db->or_like('no_prop', $q);
	$this->db->or_like('nama_prop', $q);
	$this->db->or_like('no_kab', $q);
	$this->db->or_like('nama_kab', $q);
	$this->db->or_like('no_kec', $q);
	$this->db->or_like('nama_kec', $q);
	$this->db->or_like('no_kel', $q);
	$this->db->or_like('nama_kel', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_rt', $q);
	$this->db->or_like('no_rw', $q);
	$this->db->or_like('no_prop', $q);
	$this->db->or_like('nama_prop', $q);
	$this->db->or_like('no_kab', $q);
	$this->db->or_like('nama_kab', $q);
	$this->db->or_like('no_kec', $q);
	$this->db->or_like('nama_kec', $q);
	$this->db->or_like('no_kel', $q);
	$this->db->or_like('nama_kel', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function get_nik() {
        $query = $this->db->get('penduduk');
        return $query->result_array();
    }

}

/* End of file Penduduk_model.php */
/* Location: ./application/models/Penduduk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-30 10:06:48 */
/* http://harviacode.com */