<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Permohonan_model extends CI_Model
{

    public $table = 'permohonan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nik,nama,tujuan,status,permohonan');
        $this->datatables->from('permohonan');
        //add this line for join
        //$this->datatables->join('table2', 'permohonan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('permohonan/read/$1'),'Read')." | ".anchor(site_url('permohonan/update/$1'),'Update')." | ".anchor(site_url('permohonan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    
    public function getlist() {
      //  $query = $this->db->get($this->table);
     //   return $query->result_array();
            $this->db->where('status',0);
        return $this->db->get($this->table)->result_array();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tujuan', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('permohonan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('permohonan.*, penduduk.foto,surat.keterangan surat');
        $this->db->join('penduduk','penduduk.nik=permohonan.nik','left');
        $this->db->join('surat','surat.id=permohonan.permohonan','left');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('permohonan.id', $q);
	$this->db->or_like('permohonan.nik', $q);
	$this->db->or_like('permohonan.nama', $q);
	$this->db->or_like('permohonan.tujuan', $q);
	$this->db->or_like('permohonan.status', $q);
	$this->db->or_like('permohonan.permohonan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Permohonan_model.php */
/* Location: ./application/models/Permohonan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-04 05:01:37 */
/* http://harviacode.com */