<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Registration_model extends CI_Model
{

    public $table = 'skck_registration';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,applicant_id,applicant_name,applicant_email,unit_type,reg_type,status_type,purpose_desc,staff_id,application_id,print_id,timestamps');
        $this->datatables->from('skck_registration');
        //add this line for join
        //$this->datatables->join('table2', 'skck_registration.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('registration/read/$1'),'Read')." | ".anchor(site_url('registration/update/$1'),'Update')." | ".anchor(site_url('registration/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('applicant_id', $q);
	$this->db->or_like('applicant_name', $q);
	$this->db->or_like('applicant_email', $q);
	$this->db->or_like('unit_type', $q);
	$this->db->or_like('reg_type', $q);
	$this->db->or_like('status_type', $q);
	$this->db->or_like('purpose_desc', $q);
	$this->db->or_like('staff_id', $q);
	$this->db->or_like('application_id', $q);
	$this->db->or_like('print_id', $q);
	$this->db->or_like('timestamps', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('applicant_id', $q);
	$this->db->or_like('applicant_name', $q);
	$this->db->or_like('applicant_email', $q);
	$this->db->or_like('unit_type', $q);
	$this->db->or_like('reg_type', $q);
	$this->db->or_like('status_type', $q);
	$this->db->or_like('purpose_desc', $q);
	$this->db->or_like('staff_id', $q);
	$this->db->or_like('application_id', $q);
	$this->db->or_like('print_id', $q);
	$this->db->or_like('timestamps', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Registration_model.php */
/* Location: ./application/models/Registration_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-06-27 11:13:19 */
/* http://harviacode.com */