<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sign_model extends CI_Model
{

    public $table = 'token';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,created_on,request_by,needs,token,qrcode,visited_count');
        $this->datatables->from('token');
        //add this line for join
        //$this->datatables->join('table2', 'token.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('sign/read/$1'),'Read')." | ".anchor(site_url('sign/update/$1'),'Update')." | ".anchor(site_url('sign/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_token($id)
    {
        $this->db->where('token', $id);
        return $this->db->get($this->table)->row();
    }

    function get_where($where){
        $this->db->where($where);
        return $this->db->get($this->table)->row_array();
    }
    function update_where($where, $data)
    {
        $this->db->where($where, $data);
        return $this->db->update($this->table, $data);
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('created_on', $q);
	$this->db->or_like('request_by', $q);
	$this->db->or_like('needs', $q);
	$this->db->or_like('token', $q);
	$this->db->or_like('qrcode', $q);
	$this->db->or_like('visited_count', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('created_on', $q);
	$this->db->or_like('request_by', $q);
	$this->db->or_like('needs', $q);
	$this->db->or_like('token', $q);
	$this->db->or_like('qrcode', $q);
	$this->db->or_like('visited_count', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sign_model.php */
/* Location: ./application/models/Sign_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-05 05:54:47 */
/* http://harviacode.com */