<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Skck_model extends CI_Model
{

    public $table = 'pend_skck';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $option =' <div class="dropdown relative"> <button class="dropdown-toggle button inline-block bg-theme-1 text-white">Aksi</button> <div class="dropdown-box mt-10 absolute w-40 top-0 left-0 z-20"> <div class="dropdown-box__content box p-2"> <a href="cetak/skck/$1" class="block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md">Print</a> <a href="skck/update/$1" class="block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md">Update</a> <a href="skck/delete/$1" class="block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md" onclick="javasciprt: return confirm(\'Are You Sure ?\')">Delete</a></div> </div> </div> ';

        $this->datatables->select('id,nik,nama,tujuan,status');
        $this->datatables->from('pend_skck');
        //add this line for join
        //$this->datatables->join('table2', 'pend_skck.field = table2.field');
        $this->datatables->add_column('action',$option, 'id');
       // $this->datatables->add_column('action', anchor(site_url('skck/read/$1'),'Read')." | ".anchor(site_url('skck/update/$1'),'Update')." | ".anchor(site_url('skck/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tujuan', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tujuan', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Skck_model.php */
/* Location: ./application/models/Skck_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-03 08:49:25 */
/* http://harviacode.com */